"""GitBot CLI — AI-powered git history reviewer."""

from datetime import datetime
from pathlib import Path
from typing import Annotated

import typer
from rich import print as rprint
from rich.console import Console
from rich.markdown import Markdown
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn
from rich.rule import Rule
from rich.table import Table

from gitbot.analyzer import analyze_history
from shared.data_manager import save_report
from shared.git_reader import (
    filter_commits,
    format_groups_for_llm,
    group_commits_auto,
    group_commits_by_author,
    group_commits_by_day,
    read_commits,
)

app = typer.Typer(
    name="gitbot",
    help="🤖 GitBot — AI-powered git history reviewer",
    add_completion=False,
)
console = Console()


def _get_repo_name(path: Path) -> str:
    return path.resolve().name


def _generate_markdown_report(
    repo_name: str,
    repo_path: Path,
    branch: str,
    max_commits: int,
    groups: list,
    summary: str,
) -> str:
    """Generate a complete markdown report."""
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    lines = [
        f"# 🤖 GitBot Analysis Report",
        f"",
        f"**Repository:** `{repo_name}`  ",
        f"**Path:** `{repo_path}`  ",
        f"**Branch:** `{branch}`  ",
        f"**Commits Analyzed:** {max_commits}  ",
        f"**Generated:** {timestamp}  ",
        f"",
        f"---",
        f"",
        f"## Commit Groups Summary",
        f"",
    ]

    # Add table header
    lines.append("| Group | Commits | Authors | Date Range |")
    lines.append("|-------|---------|---------|------------|")

    # Add table rows
    for g in groups:
        start, end = g.date_range
        date_str = (
            start.strftime("%Y-%m-%d")
            if start.date() == end.date()
            else f"{start.strftime('%Y-%m-%d')} → {end.strftime('%Y-%m-%d')}"
        )
        authors_str = ", ".join(g.authors[:3]) + ("..." if len(g.authors) > 3 else "")
        lines.append(f"| {g.label} | {len(g.commits)} | {authors_str} | {date_str} |")

    lines.extend([
        f"",
        f"---",
        f"",
        f"## AI Analysis",
        f"",
        summary,
        f"",
        f"---",
        f"",
        f"*Report generated by GitBot v0.1.0 — powered by Claude*",
    ])

    return "\n".join(lines)


@app.command()
def review(
    repo_path: Annotated[
        Path,
        typer.Argument(help="Path to the git repository to analyze"),
    ] = Path("."),
    max_commits: Annotated[
        int,
        typer.Option("--max-commits", "-n", help="Maximum number of commits to read"),
    ] = 300,
    group_by: Annotated[
        str,
        typer.Option(
            "--group-by", "-g",
            help="Grouping strategy: auto | day | author",
        ),
    ] = "auto",
    branch: Annotated[
        str,
        typer.Option("--branch", "-b", help="Branch to analyze"),
    ] = "HEAD",
    model: Annotated[
        str | None,
        typer.Option("--model", "-m", help="Claude model to use (overrides .env)"),
    ] = None,
    no_filter: Annotated[
        bool,
        typer.Option("--no-filter", help="Skip filtering of merge/bot/duplicate commits"),
    ] = False,
    raw: Annotated[
        bool,
        typer.Option("--raw", help="Print raw grouped commits without AI analysis"),
    ] = False,
    output: Annotated[
        Path | None,
        typer.Option("--output", "-o", help="Save report to markdown file"),
    ] = None,
    since: Annotated[
        str | None,
        typer.Option("--since", "-s", help='Only commits after this date (e.g. "2025-02-10", "1 week ago")'),
    ] = None,
    until: Annotated[
        str | None,
        typer.Option("--until", "-u", help='Only commits before this date (e.g. "2025-02-17", "yesterday")'),
    ] = None,
):
    """
    Analyze a git repository's commit history and produce an AI-powered summary.

    Examples:\n
      gitbot /path/to/my-project\n
      gitbot . --max-commits 50 --group-by day\n
      gitbot /path/to/repo --branch main --output report.md\n
      gitbot . --since "1 week ago"\n
      gitbot . --since 2025-02-01 --until 2025-02-14
    """
    repo_path = repo_path.resolve()

    if not repo_path.exists():
        rprint(f"[red]Error:[/red] Path does not exist: {repo_path}")
        raise typer.Exit(1)

    repo_name = _get_repo_name(repo_path)

    console.print()
    date_info = ""
    if since:
        date_info += f"  •  Since: {since}"
    if until:
        date_info += f"  •  Until: {until}"

    console.print(Panel(
        f"[bold cyan]GitBot[/bold cyan] analyzing [bold]{repo_name}[/bold]\n"
        f"[dim]Path: {repo_path}  •  Branch: {branch}  •  Max commits: {max_commits}{date_info}[/dim]",
        border_style="cyan",
    ))
    console.print()

    # --- Step 1: Read commits ---
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
        console=console,
    ) as progress:
        progress.add_task("Reading commit history...", total=None)
        try:
            result = read_commits(repo_path, branch=branch, max_commits=max_commits, since=since, until=until)
            commits = result.commits
        except Exception as e:
            rprint(f"[red]Failed to read repository:[/red] {e}")
            raise typer.Exit(1)

    console.print(f"[green]✓[/green] Read [bold]{len(commits)}[/bold] commits")

    if result.truncated:
        console.print(
            f"[yellow]⚠[/yellow] Branch has more than {max_commits} commits. "
            "Showing most recent. Use --max-commits to increase."
        )

    if not no_filter:
        filter_result = filter_commits(commits)
        if filter_result.removed_count > 0:
            console.print(
                f"[green]✓[/green] Filtered out [bold]{filter_result.removed_count}[/bold] "
                "irrelevant commits (merges, bots, duplicates)"
            )
        commits = filter_result.commits

    if not commits:
        rprint("[yellow]No commits found in this repository/branch.[/yellow]")
        raise typer.Exit(0)

    # --- Step 2: Group commits ---
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
        console=console,
    ) as progress:
        progress.add_task("Grouping commits...", total=None)
        if group_by == "day":
            groups = group_commits_by_day(commits)
        elif group_by == "author":
            groups = group_commits_by_author(commits)
        else:
            groups = group_commits_auto(commits)

    console.print(f"[green]✓[/green] Grouped into [bold]{len(groups)}[/bold] sections")

    # --- Step 3: Show summary table ---
    console.print()
    console.print(Rule("[dim]Commit Groups[/dim]"))
    table = Table(show_header=True, header_style="bold magenta", expand=False)
    table.add_column("Group", style="cyan", no_wrap=True)
    table.add_column("Commits", justify="right")
    table.add_column("Authors")
    table.add_column("Date Range")

    for g in groups:
        start, end = g.date_range
        date_str = (
            start.strftime("%Y-%m-%d")
            if start.date() == end.date()
            else f"{start.strftime('%Y-%m-%d')} → {end.strftime('%Y-%m-%d')}"
        )
        table.add_row(
            g.label,
            str(len(g.commits)),
            ", ".join(g.authors[:3]) + ("..." if len(g.authors) > 3 else ""),
            date_str,
        )

    console.print(table)
    console.print()

    # --- Step 4: Format for LLM ---
    formatted = format_groups_for_llm(groups)

    if raw:
        console.print(Rule("[dim]Raw Grouped History[/dim]"))
        console.print(formatted)
        raise typer.Exit(0)

    # --- Step 5: AI Analysis ---
    console.print(Rule("[dim]AI Analysis[/dim]"))
    with Progress(
        SpinnerColumn(),
        TextColumn("[progress.description]{task.description}"),
        transient=True,
        console=console,
    ) as progress:
        progress.add_task("Asking Claude to analyze the history...", total=None)
        try:
            summary = analyze_history(
                formatted, repo_name=repo_name, model=model, truncated=result.truncated
            )
        except EnvironmentError as e:
            rprint(f"[red]Configuration error:[/red] {e}")
            raise typer.Exit(1)
        except Exception as e:
            rprint(f"[red]Analysis failed:[/red] {e}")
            raise typer.Exit(1)

    console.print(Markdown(summary))
    console.print()

    # --- Step 6: Auto-save report ---
    markdown_report = _generate_markdown_report(
        repo_name=repo_name,
        repo_path=repo_path,
        branch=branch,
        max_commits=max_commits,
        groups=groups,
        summary=summary,
    )

    latest, timestamped = save_report(repo_name, "gitbot", markdown_report)
    console.print(f"[green]✓[/green] Report saved to [bold]{latest}[/bold]")
    if timestamped:
        console.print(f"[dim]  Archived: {timestamped}[/dim]")

    if output:
        output_path = output.resolve()
        try:
            output_path.write_text(markdown_report, encoding="utf-8")
            console.print(f"[green]✓[/green] Also saved to [bold]{output_path}[/bold]")
        except Exception as e:
            rprint(f"[yellow]Warning:[/yellow] Could not save report: {e}")
    console.print()

    console.print(Rule())
    console.print(
        "[dim]GitBot v0.1.0 — powered by Claude · "
        "Run with [bold]--raw[/bold] to skip AI analysis[/dim]"
    )
    console.print()


if __name__ == "__main__":
    app()
